openapi: 3.1.0
info:
  title: Policy API
  version: '1.0'
  contact:
    name: Covie Developer Support
    email: developer-help@covie.io
  termsOfService: 'https://www.covie.com/legal'
  description: 'The Policy API is intended to be used to retrieve policies and links that are created when an end-user completes the Access Workflow found within our Link Embed. This API is largely read-only, retrieving authoritative data that originates with and is controlled by an insurance company.  There are several fields which can be modified via this API in order to mange how Covie is handling and refreshing the underlying data.'
  summary: Server-to-Server API for retrieving and managing policy objects.
servers:
  - url: 'https://api.covie.io/v1'
paths:
  '/policies/{policy_id}':
    get:
      summary: Retrieve Policy
      tags:
        - policy
      operationId: get-policies-policy_id
      description: Retrieve a Policy object that was previously connected via a Link
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  '/policies/{policy_id}/documents/{document_type}':
    get:
      summary: Retrieve Policy Document
      tags:
        - policy
      operationId: get-policy-document
      description: Retrieve the contents of a Policy document
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  '/policies/{policy_id}/events':
    get:
      summary: List Policy Events
      tags:
        - policy
      operationId: list-policy-events
      description: List all events that have been triggered for the selected policy
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  /integrations:
    get:
      summary: List Integrations
      tags:
        - integration
      operationId: list-integrations
      description: List integrations associated to an application
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
    post:
      summary: Create Integration
      operationId: create-integration
      description: Creates a new integration.
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
      tags:
        - integration
  '/integrations/{integration_id}':
    get:
      summary: Get Integration
      tags:
        - integration
      operationId: get-integration
      description: Retrieve the details of an integration.
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
    patch:
      summary: Update Integration
      operationId: update-integration
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
      description: Edit the name and archived status of an integration.
      tags:
        - integration
    delete:
      summary: Delete Integration
      operationId: delete-integration
      description: Deletes an integration.
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
      tags:
        - integration
  '/links/{id}':
    get:
      summary: Retrieve link
      tags:
        - link
      operationId: get-link
      description: Retrieves a Link
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
    patch:
      summary: Update Link Settings
      operationId: update-link-settings
      tags:
        - link
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
    delete:
      summary: Delete Link
      tags:
        - link
      operationId: delete-link
      description: Deletes a link.
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  '/links/{id}/policies':
    get:
      summary: List Link Policies
      tags:
        - link
        - policy
      operationId: get-link-policies
      description: Retrieves a list of policies associated with the requested link
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  '/links/{id}/events':
    get:
      summary: List Link Events
      tags:
        - link
      operationId: get-link-events
      description: Retrieves a list of events triggered for the requested link
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  '/links/{id}/documents':
    post:
      summary: Upload Document To Link
      description: 'Attach a policy document to a Link. If the document can be parsed, select the parsed policy for sharing.'
      operationId: attach-link-document
      tags:
        - link
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  '/links/{id}/syncs':
    post:
      summary: Manually Sync Link
      tags:
        - link
      operationId: sync-link-manually
      description: Sync a tracked link with the provider using the stored user credentials
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  '/integrations/{integration_id}/links':
    post:
      summary: Initialize link
      tags:
        - link
        - integration
      operationId: initialize-link-via-integration
      description: 'Creates a link and optionally sets metadata and selects a carrier, allowing for seeding initial data before an insured continues the linking process via the embed'
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
    get:
      summary: List Integration Links
      tags:
        - link
        - integration
      operationId: get-integration-links
      description: Retrieves a list of links associated to the requested integration
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  '/integrations/{integration_id}/policies':
    get:
      summary: List Integration Policies
      tags:
        - integration
        - policy
      operationId: get-integration-policies
      description: List all policies that have been linked to an integration.
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  '/integrations/{integration_id}/links_with_policies':
    get:
      summary: List Integration Links With Policies
      tags:
        - link
        - integration
        - policy
      operationId: get-integration-links-with-policies
      description: Retrieves a list of links and selected policies associated to the requested integration
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  '/integrations/{integration_id}/providers':
    get:
      summary: Supported Providers List
      tags:
        - integration
      operationId: get-integration-providers
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
      description: 'Retrieve a list of supported carriers for a given integration, along with their identifiers.'
  '/integrations/{integration_id}/regenerate_key':
    post:
      summary: Regenerate Integration Key
      operationId: regenerate-integration-key
      description: Replaces the existing integration key with a new randomly generated key.
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
      tags:
        - integration
  '/accounts/{account_id}/mfa_requirements':
    post:
      summary: Enable Account MFA Requirement
      operationId: enable-account-mfa-required
      description: Require all account users to have an MFA application configured
      tags:
        - account
      security:
        - DashboardAuth:
            - 'account.{account_id}'
            - 'elevated.{entity_id}'
    delete:
      summary: Disable Account MFA Requirement
      operationId: disable-account-mfa-required
      description: Remove requirement for all account users to have an MFA application configured
      tags:
        - account
      security:
        - DashboardAuth:
            - 'account.{account_id}'
            - 'elevated.{entity_id}'
  '/applications/{application_id}/links':
    get:
      summary: List Application Links
      tags:
        - application
        - link
      operationId: get-application-links
      description: Lists an application's links.
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  '/applications/{application_id}/policies':
    get:
      summary: List Application Policies
      tags:
        - application
        - policy
      operationId: get-application-policies
      description: Lists an application's policies.
      security:
        - BasicAuth: []
        - DashboardAuth:
            - 'application.{application_id}'
  /webhooks:
    get:
      summary: List Webhooks
      description: List an application's configured webhooks.
      operationId: list-webhooks
      tags:
        - webhook
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
    post:
      summary: Create Webhook
      description: Create a new webhook
      operationId: create-webhook
      tags:
        - webhook
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
  '/webhooks/{webhook_id}':
    get:
      summary: Get Webhook
      description: Get the details of a webhook.
      operationId: get-webhook
      tags:
        - webhook
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
    patch:
      summary: Update Webhook
      description: Update a webhook.
      operationId: update-webhook
      tags:
        - webhook
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
  '/webhooks/{webhook_id}/events':
    get:
      summary: List Webhook Events
      description: List the events that have been triggered for a webhook.
      operationId: list-webhook-events
      tags:
        - webhook
        - event
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
  '/events/{event_id}/broadcasts':
    post:
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
      summary: Rebroadcast Event
      tags:
        - event
      operationId: post-events-event_id-broadcasts
      description: Rebroadcast an event.
  '/integrations/{integration_id}/agency_logo':
    get:
      summary: View Agency Logo
      tags:
        - integration
      operationId: get-integrations-integration_id-agency_logo
      description: View the agency logo for the hosted integration.
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
    put:
      summary: Update Agency Logo
      tags:
        - integration
      operationId: put-integrations-integration_id-agency_logo
      description: Upload the agency logo for the hosted integration.
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
    delete:
      summary: Delete Agency Logo
      tags:
        - integration
      operationId: delete-integrations-integration_id-agency_logo
      description: Delete the agency logo and/or config if present.
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
  '/integrations/{integration_id}/agent_photo':
    get:
      summary: View Agent Photo
      tags:
        - integration
      operationId: get-integrations-integration_id-agent_photo
      description: View the agent photo for the hosted integration.
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
    put:
      summary: Update Agent Photo
      tags:
        - integration
      operationId: put-integrations-integration_id-agent_photo
      description: Upload an agent photo for the hosted integration.
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
    delete:
      summary: Delete Agent Photo
      tags:
        - integration
      operationId: delete-integrations-integration_id-agent_photo
      description: Delete the agent photo and/or config if present.
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
  '/integrations/{integration_id}/brand_logo':
    get:
      summary: View Brand Logo
      tags:
        - integration
      operationId: get-integrations-integration_id-brand_logo
      description: View the brand logo for the integration.
    put:
      summary: Update Brand Logo
      tags:
        - integration
      operationId: put-integrations-integration_id-brand_logo
      description: Upload the brand logo for the hosted integration.
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
    delete:
      summary: Delete Brand Logo
      tags:
        - integration
      operationId: delete-integrations-integration_id-brand_logo
      description: Delete the brand logo and/or config if present.
      security:
        - DashboardAuth:
            - 'application.{application_id}'
        - BasicAuth: []
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      description: An application's Client ID and Client Secret are combined to form the username and password.
    DashboardAuth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: ''
          tokenUrl: ''
          refreshUrl: ''
          scopes:
            user: Used to manage user configuration and to request an account scoped token.
            'account.{account_id}': Used to manage accounts and configure applications. Permission is limited to the account identified.
            'application.{application_id}': Used to view and manage data within an application. Permission is limited to the application identified.
            'elevated.{entity_id}': Short lived token used for performing sensitive functionality. Permission is limited to the entity identified.
      description: Authentication system used by the Client Dashboard.
tags:
  - name: account
    description: <SchemaDefinition schemaRef="./models/AccountWithRole.yaml" />
    x-displayName: Account
  - name: address
    description: <SchemaDefinition schemaRef="./models/Address.yaml" />
    x-displayName: Address
  - name: application
    description: <SchemaDefinition schemaRef="./models/Application.yaml" />
    x-displayName: Application
  - name: carrier
    description: <SchemaDefinition schemaRef="./models/Carrier.yaml" />
    x-displayName: Carrier
  - name: coverage
    description: <SchemaDefinition schemaRef="./models/Coverage.yaml" />
    x-displayName: Coverage
  - name: currencyvalue
    description: <SchemaDefinition schemaRef="./models/CurrencyValue.yaml" />
    x-displayName: CurrencyValue
  - name: discount
    description: <SchemaDefinition schemaRef="./models/Discount.yaml" />
    x-displayName: Discount
  - name: documentref
    description: <SchemaDefinition schemaRef="./models/DocumentRef.yaml" />
    x-displayName: DocumentRef
  - name: driver
    description: <SchemaDefinition schemaRef="./models/Driver.yaml" />
    x-displayName: Driver
  - name: email
    description: <SchemaDefinition schemaRef="./models/EMail.yaml" />
    x-displayName: E-Mail
  - name: event
    description: <SchemaDefinition schemaRef="./models/Event.yaml" />
    x-displayName: Event
  - name: integration
    description: <SchemaDefinition schemaRef="./models/Integration.yaml" />
    x-displayName: Integration
  - name: interest
    description: <SchemaDefinition schemaRef="./models/Interest.yaml" />
    x-displayName: Interest
  - name: link
    description: <SchemaDefinition schemaRef="./models/Link.yaml" />
    x-displayName: Link
  - name: location
    description: <SchemaDefinition schemaRef="./models/Location.yaml" />
    x-displayName: Location
  - name: name
    description: <SchemaDefinition schemaRef="./models/Name.yaml" />
    x-displayName: Name
  - name: oauth-client
    description: <SchemaDefinition schemaRef="./models/OauthClient.yaml" />
    x-displayName: OAuth Client
  - name: percentagevalue
    description: <SchemaDefinition schemaRef="./models/PercentageValue.yaml" />
    x-displayName: PercentageValue
  - name: periodvalue
    description: <SchemaDefinition schemaRef="./models/PeriodValue.yaml" />
    x-displayName: PeriodValue
  - name: phone
    description: <SchemaDefinition schemaRef="./models/Phone.yaml" />
    x-displayName: Phone
  - name: policy
    description: <SchemaDefinition schemaRef="./models/Policy.yaml" />
    x-displayName: Policy
  - name: policyholder
    description: <SchemaDefinition schemaRef="./models/Policyholder.yaml" />
    x-displayName: Policyholder
  - name: relativevalue
    description: <SchemaDefinition schemaRef="./models/RelativeValue.yaml" />
    x-displayName: RelativeValue
  - name: user
    description: <SchemaDefinition schemaRef="./models/User.yaml" />
    x-displayName: User
  - name: vehicle
    description: <SchemaDefinition schemaRef="./models/Vehicle.yaml" />
    x-displayName: Vehicle
  - name: webhook
    description: <SchemaDefinition schemaRef="./models/Webhook.yaml" />
    x-displayName: Webhook
x-tagGroups:
  - name: API Reference
    tags:
      - link
      - policy
      - application
      - policyholder
      - location
      - vehicle
      - driver
      - coverage
      - discount
      - carrier
      - interest
      - address
      - phone
      - email
      - documentref
      - currencyvalue
      - percentagevalue
      - relativevalue
      - periodvalue
      - name
      - event
      - billing